-- Staging del Censo Económico: limpieza de strings, clasificación de nivel geográfico,
-- y paso de los 98 indicadores sin transformación.
with
    fuente as (select * from {{ source("sieej", "ce_datos") }}),

    limpio as (
        select
            id as id_fuente,
            anio,
            nullif(trim(entidad), '') as cve_ent,
            nullif(trim(municipio), '') as cve_mun,
            nullif(trim(codigo), '') as codigo_actividad,
            nullif(trim(id_estrato), '') as id_estrato,
            nullif(trim(sector), '') as sector,
            nullif(trim(subsector), '') as subsector,
            nullif(trim(rama), '') as rama,
            nullif(trim(subrama), '') as subrama,
            nullif(trim(clase), '') as clase,
            nullif(trim(cvegeo), '') as cvegeo,
            case
                when trim(entidad) = '' and trim(municipio) = ''
                then 'nacional'
                when trim(entidad) <> '' and trim(municipio) = ''
                then 'entidad'
                when trim(entidad) <> '' and trim(municipio) <> ''
                then 'municipio'
            end as nivel_geografico,

            -- 98 indicadores: se pasan tal cual
            ue,
            h001a,
            h000a,
            h010a,
            h020a,
            i000a,
            j000a,
            k000a,
            m000a,
            a111a,
            a121a,
            a131a,
            a211a,
            a221a,
            p000c,
            q000a,
            q000b,
            a700a,
            a800a,
            q000c,
            q000d,
            p000a,
            p000b,
            o010a,
            o020a,
            m700a,
            p030c,
            a511a,
            m020a,
            m050a,
            m091a,
            h001b,
            h001c,
            h001d,
            h000b,
            h000c,
            h000d,
            h010b,
            h010c,
            h010d,
            h101a,
            h101b,
            h101c,
            h101d,
            h203a,
            h203b,
            h203c,
            h203d,
            h020b,
            h020c,
            h020d,
            i000b,
            i000c,
            i000d,
            i100a,
            i100b,
            i100c,
            i100d,
            i200a,
            i200b,
            i200c,
            i200d,
            j010a,
            j203a,
            j300a,
            j400a,
            j500a,
            j600a,
            k010a,
            k020a,
            k030a,
            k311a,
            k042a,
            k412a,
            k050a,
            k610a,
            k620a,
            k060a,
            k070a,
            k810a,
            k820a,
            k910a,
            k950a,
            k096a,
            k976a,
            k090a,
            m010a,
            m030a,
            m090a,
            p100a,
            p100b,
            p030a,
            p030b,
            q010a,
            q020a,
            q030a,
            q400a,
            q900a
        from fuente
    )

select *
from limpio
