-- Staging del Censo de Población: clasificación de nivel geográfico usando
-- la convención INEGI de códigos cero, y paso de los ~222 indicadores.
with
    fuente as (select * from {{ source("sieej", "cp_datos") }}),

    limpio as (
        select
            id as id_fuente,
            anio,
            trim(entidad) as cve_ent,
            trim(mun) as cve_mun,
            trim(loc) as cve_loc,
            trim(ageb) as cve_ageb,
            trim(mza) as cve_mza,
            trim(nom_ent) as nombre_entidad,
            trim(nom_mun) as nombre_municipio,
            trim(nom_loc) as nombre_localidad,
            trim(cvegeo) as cvegeo,
            case
                when trim(entidad) = '00'
                then 'nacional'
                when trim(mun) = '000' and trim(loc) = '0000'
                then 'entidad'
                when trim(loc) = '0000' and trim(ageb) = '0000' and trim(mza) = '000'
                then 'municipio'
                when trim(ageb) = '0000' and trim(mza) = '000'
                then 'localidad'
                when trim(mza) = '000'
                then 'ageb'
                else 'manzana'
            end as nivel_geografico,

            -- ~222 indicadores: se pasan tal cual
            pobtot,
            pobfem,
            pobmas,
            p_0a2,
            p_0a2_f,
            p_0a2_m,
            p_3ymas,
            p_3ymas_f,
            p_3ymas_m,
            p_5ymas,
            p_5ymas_f,
            p_5ymas_m,
            p_12ymas,
            p_12ymas_f,
            p_12ymas_m,
            p_15ymas,
            p_15ymas_f,
            p_15ymas_m,
            p_18ymas,
            p_18ymas_f,
            p_18ymas_m,
            p_3a5,
            p_3a5_f,
            p_3a5_m,
            p_6a11,
            p_6a11_f,
            p_6a11_m,
            p_8a14,
            p_8a14_f,
            p_8a14_m,
            p_12a14,
            p_12a14_f,
            p_12a14_m,
            p_15a17,
            p_15a17_f,
            p_15a17_m,
            p_18a24,
            p_18a24_f,
            p_18a24_m,
            p_15a49_f,
            p_60ymas,
            p_60ymas_f,
            p_60ymas_m,
            rel_h_m,
            pob0_14,
            pob15_64,
            pob65_mas,
            prom_hnv,
            pnacent,
            pnacent_f,
            pnacent_m,
            pnacoe,
            pnacoe_f,
            pnacoe_m,
            pres2015,
            pres2015_f,
            pres2015_m,
            presoe15,
            presoe15_f,
            presoe15_m,
            p3ym_hli,
            p3ym_hli_f,
            p3ym_hli_m,
            p3hlinhe,
            p3hlinhe_f,
            p3hlinhe_m,
            p3hli_he,
            p3hli_he_f,
            p3hli_he_m,
            p5_hli,
            p5_hli_nhe,
            p5_hli_he,
            phog_ind,
            pob_afro,
            pob_afro_f,
            pob_afro_m,
            pcon_disc,
            pcdisc_mot,
            pcdisc_vis,
            pcdisc_leng,
            pcdisc_aud,
            pcdisc_mot2,
            pcdisc_men,
            pcon_limi,
            pclim_csb,
            pclim_vis,
            pclim_haco,
            pclim_oaud,
            pclim_mot2,
            pclim_re_co,
            pclim_pmen,
            psind_lim,
            p3a5_noa,
            p3a5_noa_f,
            p3a5_noa_m,
            p6a11_noa,
            p6a11_noaf,
            p6a11_noam,
            p12a14noa,
            p12a14noaf,
            p12a14noam,
            p15a17a,
            p15a17a_f,
            p15a17a_m,
            p18a24a,
            p18a24a_f,
            p18a24a_m,
            p8a14an,
            p8a14an_f,
            p8a14an_m,
            p15ym_an,
            p15ym_an_f,
            p15ym_an_m,
            p15ym_se,
            p15ym_se_f,
            p15ym_se_m,
            p15pri_in,
            p15pri_inf,
            p15pri_inm,
            p15pri_co,
            p15pri_cof,
            p15pri_com,
            p15sec_in,
            p15sec_inf,
            p15sec_inm,
            p15sec_co,
            p15sec_cof,
            p15sec_com,
            p18ym_pb,
            p18ym_pb_f,
            p18ym_pb_m,
            graproes,
            graproes_f,
            graproes_m,
            pea,
            pea_f,
            pea_m,
            pe_inac,
            pe_inac_f,
            pe_inac_m,
            pocupada,
            pocupada_f,
            pocupada_m,
            pdesocup,
            pdesocup_f,
            pdesocup_m,
            psinder,
            pder_ss,
            pder_imss,
            pder_iste,
            pder_istee,
            pafil_pdom,
            pder_segp,
            pder_imssb,
            pafil_ipriv,
            pafil_otrai,
            p12ym_solt,
            p12ym_casa,
            p12ym_sepa,
            pcatolica,
            pro_crieva,
            potras_rel,
            psin_relig,
            tothog,
            hogjef_f,
            hogjef_m,
            pobhog,
            phogjef_f,
            phogjef_m,
            vivtot,
            tvivhab,
            tvivpar,
            vivpar_hab,
            vivparh_cv,
            tvivparhab,
            vivpar_des,
            vivpar_ut,
            ocupvivpar,
            prom_ocup,
            pro_ocup_c,
            vph_pisodt,
            vph_pisoti,
            vph_1dor,
            vph_2ymasd,
            vph_1cuart,
            vph_2cuart,
            vph_3ymasc,
            vph_c_elec,
            vph_s_elec,
            vph_aguadv,
            vph_aeasp,
            vph_aguafv,
            vph_tinaco,
            vph_cister,
            vph_excsa,
            vph_letr,
            vph_drenaj,
            vph_nodren,
            vph_c_serv,
            vph_ndeaed,
            vph_dsadma,
            vph_ndacmm,
            vph_snbien,
            vph_refri,
            vph_lavad,
            vph_hmicro,
            vph_autom,
            vph_moto,
            vph_bici,
            vph_radio,
            vph_tv,
            vph_pc,
            vph_telef,
            vph_cel,
            vph_inter,
            vph_stvp,
            vph_spmvpi,
            vph_cvj,
            vph_sinrtv,
            vph_sinltc,
            vph_sincint,
            vph_sintic
        from fuente
    )

select *
from limpio
